README.md, bin/ditto.js, package.json
Update commands (and README) with `ditto` instead of `ditto-cli`
=> Change `ditto-cli` to `ditto`

lib/config.js, lib/init/project.js, lib/init/token.js, lib/output.js, lib/pull.js, lib/select-project.js
Updates to handle revoked API keys: when key that's saved can't be found in our database, clear existing one from from `.config/ditto` file and prompt the user to enter a new one.
Updates to handle errors returned by `/projects/:id` (specifically, if requested project doesn't have dev mode on).
- associated Ditto API PR: https://github.com/dittowords/ditto-app/pull/306
- run `pull` command with revoked key, enter new one -> pull executed
- run `project` command with revoked key (and then quit before enter new one) -> displays message
- requested project doesn't have dev mode on:
- Tested locally (local CLI and local API): https://www.notion.so/dittov3/handle-revoke-keys-Ditto-CLI-Testing-0a8ce467dbea43ed9cc053e8e9023c6f
- Once merged into CLI, will test again with staging API and …
=> Handle revoked api keys

bin/ditto.js, lib/add-project.js, lib/config.js, lib/init/init.js, lib/init/project.js, lib/pull.js, lib/remove-project.js, lib/utils/getSelectedProjects.js, lib/utils/listProjects.js, lib/utils/projectsToText.js, lib/utils/promptForProject.js, package.json
**Associated PR (blocks this one)**: https://github.com/dittowords/ditto-app/pull/394
This PR adds support to the CLI for:
- adding new projects to `ditto/config.yaml`
- removing existing projects to `ditto/config.yaml`
- pulling the text data from multiple projects to be stored in `text.json`
Other changes of note:
- `ditto-cli project` now behaves the same as `ditto-cli project add`
Developers using our CLI currently have to `cd` into subdirectories and `pull` multiple times when they have more than one Ditto project associated with a code repository they're working in. Adding the ability to `pull` multiple Ditto projects into a single `text.json` file in the root of the project will:
- cut down manual actions by forcing developers to `pull` only once
- save time by enabling developers …
=> Support pulling and saving multi-project text data

bin/ditto.js, lib/add-project.js, lib/init/project.js, lib/init/token.js, package.json
The CLI was incorrectly returning a status code of 2 (signaling that something went wrong with the execution of the program) when a user attempts to add a project to a YAML file already containing all of the projects in the workspace.
This PR fixes that to return a status code of 0 in that instance; status code 2 should only be used when the program encounters an error causing it to exit early.
Linear ticket:
https://linear.app/dittowords/issue/DIT-271/fix-ditto-cli-error-from-adding-project-to-yaml-file
Before:
After:
For some reason I couldn't get the error to throw by running the CLI directly (note that in Jason's original report it was NPM itself that was throwing the error based on the status code); I instead created a test project with this in `package.json`:
```json
"scripts": { …
```
=> [DIT-271] Fix error when running `project add` on full YAML file

README.md, lib/pull.js, package.json
Prior to this PR, files would always be written for every variant in the workspace if `variants: true` was specified. This PR changes that behavior so that variant files are only written for projects that actually contain values for a given variant.
https://github.com/dittowords/ditto-app/pull/687 is a companion PR to this one, but its functionality is not required for this PR to be tested - it only reduces the number of requests that need to be made.
https://linear.app/dittowords/issue/DIT-571/cli-only-output-variant-files-for-variants-with-values-in-specified
before:
after:
-  [x] Pull with `variants: true` and confirm that no blank files are generated
=> [DIT-571] Only write variant files for projects that have them

README.md, lib/config.js, lib/init/init.js, lib/init/project.js, lib/pull.js, lib/utils/getSelectedProjects.js, lib/utils/projectsToText.js, lib/utils/sourcesToText.js, package.json
Adds support for setting `components: true` in `config.yml` to fetch data from the component library. 
Previously, this was only possible by including `ditto_component_library` as a project in the `projects` array. That method was unintuitive and misleading since the format and nature of the component library is different in a number of fundamental ways from a project. 
Additionally, we want the component library to be a first-class citizen in CLI usage, not an afterthought. This is the first step of several to get us to that point.
https://linear.app/dittowords/issue/DIT-815/update-cli-for-component-library
An example of a valid configuration file using the new option:
I tested using the `example` project in `ditto-react` by running `yarn add @dittoworlds/cli@beta` in the `example` …
=> [DIT-815] Add support for 'components' property

lib/config.js, lib/utils/getSelectedProjects.js
- Defines `projectNames` as a `Set` to match the code that was already refactored to expect `Set` methods. This bug was causing the `pull` command to crash when projects other than the component library were specified.
- Fixes a casing typo on `contentJson` that was causing the `project add` command to crash.
Fixes bugs introduced by https://github.com/dittowords/cli/pull/22, reported in https://github.com/dittowords/cli/issues/23.
=> Fix typos crashing `project add` and `pull` commands

README.md, lib/config.js, lib/init/token.js, package.json
Support passing an API token via an environment variable `DITTO_API_KEY`.
If environment variable is set, it will be used with precedence over any tokens stored in `~/.config/ditto`.
Interacting with the Ditto CLI from CI environments or deployed applications will be made way easier by allowing the environment variable as an alternative to the current config file approach.
>- [ ] no command (should just display help)
>- [ ] `project`
>- [ ] `project add`
>- [ ] `project remove`
>- [ ] `pull`
>- [ ] no command (should just display help)
>- [ ] `project`
>- [ ] `project add`
>- [ ] `project remove`
>- [ ] `pull`
=> Support passing API token via environment variable

lib/consts.js
Allows users to override the text output directory using DITTO_TEXT_DIR env variable
often with typescript/etc, modules cannot resolve paths at the repo root or outside of the `src` or equivalent directory
=> Allow users to override the output directory

README.md, lib/config.ts, lib/pull.test.ts, lib/pull.ts, lib/types.ts, package.json
This pull request adds a new optional config value called `status` which will filter text items/components when running `ditto pull`.
Create a workspace with the following:
- Workspace components with variants and various statuses
- A project with text items that have variants and various statuses
Verify expected values with the following config values:
=> Add status filtering

README.md, lib/config.ts, lib/pull.ts, lib/types.ts, package.json
Adds the ability to pull down rich text data. This uses the `includeRichText` API parameter that is yet to be released, so we should hold off on testing and merging this PR until that is out.
=> Add rich text parameter

lib/init/token.ts, package.json
Small change to log the error when `/token-check` fails. This should catch and log cert errors that some users may encounter.
This PR may change depending on how we handle self-signed cert errors.
=> Log error when failing token check

.gitignore, lib/config.ts, lib/http/fetchVariants.ts, lib/init/project.ts, lib/pull.ts, lib/types.ts, lib/utils/generateJsDriver.ts, tsconfig.json
- Support specifying a list of component folders that should be filtered by
- Refactor file output structure to always be `{source_name}__{variant_name}.{extension}`. This is a major win for simplification, and is only possible as a breaking change and without supporting the `full` format.
https://linear.app/dittowords/issue/DIT-3310/cli
=> [DIT-3310] Revamp file output & add component folder support

lib/ditto.ts, lib/generate-suggestions.test.ts, lib/generate-suggestions.ts, lib/http/fetchComponents.ts, lib/replace.test.ts, package.json, yarn.lock
This PR adds a new `generate-suggestions` command which will scan through the current repository for strings that match Ditto components. The files must be either `jsx` or `tsx`.
Note: The `generate-suggestions` command is not officially supported by Ditto yet.
Usage: ditto-cli generate-suggestions
Sample output:
=> Add generate-suggestions command

lib/ditto.ts, package.json
This pull request adds a new feature to the ditto-cli command-line tool, allowing users to view the current version of the application by using the -v or --version flag. The version number is retrieved from the package.json file, ensuring that it stays up-to-date with the actual package version.
Changes:
- Import package.json in the main script to access the version number.
- Define a VERSION constant that retrieves the version number from the imported package.json.
- Update the setupOptions() function to use the version() method of the Commander program, which overrides the built-in version option.
These changes make it easier for users to quickly check the installed version of the ditto-cli tool, facilitating better debugging and ensuring they are using the correct version.
=> Add version option to CLI

lib/replace.ts, package.json
The replace function was failing for a component with text `?`. This should escape all regex characters.
=> Fix regex escape for replacing

README.md, lib/api.ts, lib/http/fetchComponents.ts, lib/http/fetchVariants.ts, lib/init/project.ts, lib/init/token.ts, lib/pull.test.ts, lib/pull.ts, lib/types.ts, package.json
Adds explicit support for new ICU format and fixes some problems inherent to the previous implementation of the API client.
https://linear.app/dittowords/issue/DIT-3960/update-cli-readme-w-icu-format
=> [DIT-3960] Add full ICU support

lib/ditto.ts, lib/generate-suggestions.test.ts, lib/generate-suggestions.ts, testfiles/test1.jsx
Adds a new flag to the `generate-suggestions` command to specify specific files to search through (comma separated list). Will override the directory flag.
=> [DIT-4197] Add files flag to generate-suggestions

lib/ditto.ts, lib/generate-suggestions.test.ts, lib/generate-suggestions.ts, package.json, testfiles/test1.jsx
Improved the speed of generating suggestions by no longer opening each file for each component. Now we iterate the components for each file.
Running on the ditto codebase
Previous:
New:
=> Speed improvement for generate-suggestions

lib/config.ts, lib/pull.ts, lib/types.ts
Adds support for optionally specifying a list of formats in the `format` property.
https://linear.app/dittowords/issue/DIT-4270/pull-down-strings-and-stringsdict
```yml
format:
- ios-strings
- ios-stringsdict
```
=> [DIT-4270] Support pulling multiple formats at once

lib/pull.test.ts, lib/pull.ts
Updates per-filetype logic that determines whether or not API data should be written to disk to handle variant metadata.
Also fixes miscellaneous `pull.test.ts` tests that have been broken for quite some time.
https://linear.app/dittowords/issue/DIT-4687/update-cli-empty-file-detection-logic-to-exclude-variant-metadata
Also fixes DIT-4116
1. Create two variants in your workspace
2. Apply one of the variants to one or more components 
3. Set your test CLI config as follows:
```yaml
sources:
components: 
enabled: true
variants: true
```
4. Run `yarn start pull` in the CLI directory
5. Confirm that a file is written to disk for the variant that is used
6. Confirm that a file is NOT written to disk for the unused variant
=> [DIT-4687] Update CLI empty file detection logic to exclude variant metadata, fix tests

lib/pull.ts
Ensure generated files end with new lines to comply with POSIX standard and not break tools.
https://linear.app/dittowords/issue/DIT-4524/ensure-generated-output-files-have-trailing-newlines
1. On `master`, run `yarn start` and `cat` the contents of an output file -- observe that a `%` displays at the end of the output, indicating that the file ends in a "partial" line (i.e. no new line at the end)
2. Check out this branch
3. Run `yarn start` and `cat` the contents of the same file -- observe the absence of `%`, indicating that the file correctly terminates with a new line
=> [DIT-4524] (v4) Ensure generated output files have trailing newlines

lib/pull.ts, lib/types.ts
Adds support for source-level configuration flags: 
- "status" 
- "exclude_components" (projects only)
"status" can still be specified at the top-level as a default, but the specification of source-specific "status" will override it.
https://linear.app/dittowords/issue/DIT-4704/source-specific-cli-config-flags
Components & projects
Projects only
1. Create multiple component folders in your component library
2. Create components in each component folder
3. Give all components diverse statuses
4. In two different projects:
1. Attach some text items to components
2. Assign diverse statuses to text items
5. Setup another project with diverse statuses and some attached components
6. In the terminal where you'll use the CLI, point at your local API: `export DITTO_API_HOST=http://localhost:3001` …
=> [DIT-4704] (v4) Add support for source-specific CLI config flags

lib/config.ts, lib/init/project.ts, lib/pull.ts, lib/types.ts, lib/utils/generateJsDriver.ts
- Write files for component data on a per folder, per variant basis (previously was only on a per variant basis)
```
ditto_component_library__base.json
ditto_component_library__spanish.json
components__root__base.json
components__root__spanish.json
components__some-folder__base.json
components__some-folder__spanish.json
```
- Gets rid of `sources.components.enabled`, instead supporting `sources.components: true` (for explicitly enabled with no configuration) or implicitly understanding that components should be fetched when `sources.components` is a configuration object
```yml
sources:
components:
enabled: true
sources:
components:
enabled: true
folders:
...
sources:
components: true
sources:
components:
folders:
...
```
- Adds support for a `sources.components.root` property -- similar …
=> [DIT-4720] (v4) Component support overhaul

lib/pull.ts, lib/types.ts, lib/utils/generateJsDriver.ts
Generate backwards-compatible index.js driver format that includes all component keys for a given variant (independent of the folders they're in) under a single key.
This is done by generating a file that looks like this:
```js
module.exports = {
ditto_component_library: {
base: {
...require('./components__root__base.json'),
...require('./components__folder-1__base.json'),
},
some_variant: {
...require('./components__root__some_variant.json'),
...require('./components__folder-1__some_variant.json'),
},
}
}
```
This makes it so that the CLI v4 is backwards compatible with previous `ditto-react` versions.
https://linear.app/dittowords/issue/DIT-4784/update-indexjs-driver-file-to-be-backwards-compatible-for-ditto-react
Now that components are written on a per-folder basis, we need to update …
=> [DIT-4784] (v4) Generate backwards-compatible index.js driver file for `ditto-react` compat

lib/pull.ts, package.json
- Ensure that the Sentry environment is correctly set to `production` when errors are captured
- Log the Sentry event ID to the console for customer reference
https://linear.app/dittowords/issue/DIT-4793/include-sentry-event-id-in-error-messages
=> [DIT-4793] (v4) Include Sentry event ID in error messages, fix publish environment

lib/config.ts, lib/types.ts
Rename `ios_locales` -> `iosLocales` for consistency with other camelCase properties.
=> Rename ios_locales property for naming convention consistency

lib/utils/determineModuleType.ts, lib/utils/generateJsDriver.ts, package.json
Refactors `generateJsDriver` to depend on the `type` property of the nearest `package.json` file.
- if `type` is `module`, an ESM module is generated
- otherwise, a CommonJS module is generated 
https://linear.app/dittowords/issue/DIT-5321/make-ditto-react-work-with-default-vite-react-setup
=> [DIT-5321] Support generating ESM JavaScript driver

lib/http/fetchComponentFolders.ts, lib/http/fetchComponents.ts, lib/http/fetchVariants.ts, lib/init/project.ts, lib/pull.ts
Migrate all endpoints to `/v1`
https://linear.app/dittowords/issue/DIT-5338/migrate-cli-to-use-v1-api-endpoints
1. Create a full config with components and projects
```yaml
sources:
components:
folders:
- id: some-folder
name: Some Folder
root: true
projects:
- id: xxx-xxx-xxx
name: Some Project
format: flat
variants: true
```
Test with a bunch of different formats:
Test the project add command (undocumented as of new release since we're going to revamp the way that managing the config file works):
```yaml
sources:
components:
root: true
format: flat
variants: true
```
=> [DIT-5338] Migrate CLI to use v1 API Endpoints

lib/component-folders.ts, lib/config.test.ts, lib/ditto.ts, lib/generate-suggestions.test.ts, lib/http/fetchComponentFolders.ts, lib/init/token.test.ts, lib/pull.ts, lib/replace.ts, package.json
Adds a flag to return sample data for the components-folder command.
=> Add sample-data field to the components-folder command

lib/ditto.ts, lib/generate-suggestions.ts, lib/http/fetchComponents.ts, package.json
This PR makes a change to take into account what command is being run before deciding to run init() or not.
Also includes two minor improvements:
- Explicitly use `structured` format when querying for components
- Ignore white space only lines of code and components when generating suggestions
The Ditto VSCode extension runs commands such as `generate-suggestions`, `component-folders`, and `replace`. These commands don't rely on local data (it calls the Ditto API) and thus doesn't require a `config.yml` to be present. Because of this, it is unnecessary to run init() when these commands are called.
=> Only run init() on commands that need it

lib/pull.ts, lib/utils/cleanFileName.test.ts, lib/utils/cleanFileName.ts
This PR refines the logic to create .js filenames; we make sure emojis don't turn into weird hyphens.
[DIT-5759 : Component Folder Dev IDs do not handle emojis well](https://linear.app/dittowords/issue/DIT-5759/component-folder-dev-ids-do-not-handle-emojis-well)
=> DIT-5759: component folder dev IDs properly exclude emojis

lib/pull.test.ts, lib/pull.ts, lib/types.ts
When the `nested` format is specified in the configuration file, instead of processing the files in the expected nested format, the CLI tool silently defaults to the `flat` format. This behavior contradicts the documented capabilities of the tool and can lead to confusion for users relying on the nested format.
In this pull request, I have implemented changes to ensure that the @dittowords/cli tool correctly processes and outputs files in the "nested" JSON format when it is specified. 
This pull request contains a fix to align the tool's behavior with the documented features and expected functionality by adding `nested` value to all necessary constants.
Additionally, this pull request introduces two minor enhancements:
- adding of a new type named `SupportedExtension`, mirroring the …
=> Fix: Support for Nested JSON Format

lib/ditto.ts, lib/http/fetchVariants.ts, lib/pull.ts, package.json
This PR adds the `--sample-data` flag to the `pull` command and is intended to allow support for sample data to be included in the `pull` execution. With this PR, only variants will be supported.
=> [DIT-6177] Add pull --sample-data flag for variants

lib/init/token.ts
Updates the printed out url the url to where a user can create a ditto api key.
Current URL points and outdated /user endpoint.
=> Update url for creating a new API key

lib/init/token.ts, lib/utils/quit.ts, package.json
Fixes an issue where the CLI would become unresponsive but fail to fully exit when the user attempted to use Ctrl + C to bail out of the process.
https://linear.app/dittowords/issue/DIT-6379/fix-cli-hanging-when-ctrlc-out-of-token-collection-prompt
1. Remove the file `~/.config/ditto`
2. Run `yarn start pull`
3. At the prompt, hit Ctrl + C
4. Confirm that the CLI exits and control is immediately returned to the user
=> [DIT-6379] Fix terminal hanging when Ctrl + C pressed during `pull` and token prompt

.sentryclirc, lib/config.ts, lib/pull.test.ts, lib/pull.ts, lib/types.ts, package.json
- feat: add config option for disabling js driver file generation
https://linear.app/dittowords/issue/DIT-6730/feature-request-for-a-cli-option-to-not-create-js-driver-files
=> [DIT-6730] Add `disableJsDriver` option

lib/src/formatters/frameworks/json/base.ts, lib/src/formatters/frameworks/json/i18next.ts, lib/src/formatters/json.ts, lib/src/formatters/mixins/javascriptCodegenMixin.ts, lib/src/formatters/shared/base.ts, lib/src/outputs/json.ts
Adds support for a `type` field used by the i18next framework to generate commonjs or ES6 module syntax in the generated javascript driver file. Defaults to commonjs
- Updated `JSONFormatter` and `BaseFramework` to use `outDir` instead of `outputDir` for improved consistency.
- Introduced module type handling in `I18NextFramework` to support both CommonJS and ES module formats.
- Added methods for generating require statements and module exports to streamline output generation.
- Enhanced Zod schema for JSON output to include optional module type specification.
=> Add  module type support in i18next framework output file

lib/src/index.ts, lib/src/outputs/json.ts, lib/src/services/projectConfig.ts, lib/src/utils/DittoError.ts, lib/src/utils/errors.ts
Creates a new custom error class `DittoError` that allows use to pass specific error data from the call site to the error handler. This is similar to `ApiError` in the main app, but with stronger typing since we're starting from scratch.
Updates the error messages we surface to the user when we encounter a failure in the config file.
1. If we fail to read the yaml file (not valid format at all), the error message will tell them to make sure it's valid yaml
2. If it's valid yaml but doesn't match our schema, the error message will attempt to tell them which fields are extra or have invalid typing
3. Sends the zod issues in to sentry as `extra` -- this seemed to be the best place to put unconstrained metadata, but I'm not sure how to test this. …
=> [DIT-10128] Better error messaging for config errors
